### ISSUE TITLE
importing large s3 files

### ISSUE THREAD

**Issue by ghost** [awslabs/aws-lambda-redshift-loader#112]
AWS Lambda has a limit of 5 minutes for execution, I have files that will take longer than 5 minutes to run the COPY command for the complete import. 

How does this solution address COPY commands that will take longer than 5 minutes?

**Comment by AmitThakkar** [comment]
+1

**Comment by alexhogberg** [comment]
Since this solution is lambda based and the COPY command would run in an instance of the lambda your COPY command needs to take less than 5 minutes to complete (it actually needs to take even less than that, since it needs time to update batchstatus etc). I would suggest trying to split the incoming file into smaller chunks so that you can complete the load in several smaller COPY's instead of one large, but perhaps that isn't possible in your situation?

If you have several incoming files I would then suggest you lower your batchSize to a smaller number, making sure that loads happen more often and at smaller scale. You might also consider increasing the number of nodes in your redshift cluster to increase the performance of the COPY command (keeping it in the same multiple of the number of files configured).

**Comment by wrschneider** [comment]
The limit is now 15 minutes, which may make this a little less of an issue

**Comment by ghost** [comment]
AWS Glue also has pyshell jobs you can run instead of a lambda, they can be schedule, and triggered manually and this doesn't have a time limit.
