### ISSUE TITLE
Dynamo Provisioned Throughput exceptions cause writes to a redshift table to become locked

### ISSUE THREAD

**Issue by frankfarrell** [awslabs/aws-lambda-redshift-loader#145]
If we have a surge in traffic and hit dynamo provisioned throughput exceptions, write to the corresponding redshift table becomes locked. 

To resolve we need to manually query dynamo for the last batch id that is stuck on error and with that id run: 
`resetCurrentBatch.js ap-southeast-2 <prefix> <batchid> `
Then for each batch id in that table that is in error or locked state, run: 
`node reprocessBatch.js ap-southeast-2 <batchid> <prefix>`

Would a lambda that reacts to some log event in the redshift loader logs through cloudwatch run the above set of steps to resolve? I would be happy to contribute if you could advise me on what log pattern to watch. 

Thanks

**Comment by IanMeyers** [comment]
Possibly. Can you try using DynamoDB Autoscaling to prevent this issue ever arising?

**Comment by frankfarrell** [comment]
We have DynamoDB autoscaling  enabled, but it doesn't react fast enough to the spike in traffic. The alternative would be to use exponential backoff in the dynamodb calls? I haven't checked the code properly to see how the issue arises. 

An alternative would be to subscribe a lambda to the sqs channel, what do you think?

**Comment by seb-steuer** [comment]
Hi,

So even more concerning for me is throttling on LambdaRedshiftBatches table and how to recover from batches not being created due to DDB throttling

I've got a settings with a batch size of 10 and after dropping 300 files to s3 bucket and with not enough DDB capacity I got only 6 batches created instead of expected 30

when I look into LambdaRedshiftProcessedFiles i see that there is plenty of rows without batchId value

How can I recover from such scenario?

Kind regards

**Comment by IanMeyers** [comment]
Please deploy version 2.5.5 of the module, at which point you can use the new `--reprocess` option with `processedFiles.js`, which will perform an in-place copy which is now treated as an 'original' event by the loader, which will do a reprocess.

**Comment by seb-steuer** [comment]
Hi,

That's great, I'll give it a try soon.

Thank you
