### ISSUE TITLE
Lambda times out when trying to get config item from DynamoDB

### ISSUE THREAD

**Issue by landoooo** [awslabs/aws-lambda-redshift-loader#150]
Hi. We are trying to use the redshift loader. We went through the setup and we have at the moment the three DynamoDB tables created, the config for the bucket there inside and a lambda that reacts to every file created on the bucket we defined. Our problem is, the lambda gets stuck on the method getConfigWithRetry (index.js) when trying to get items from DynamoDB till the lambda times out. The timeout has been increased to 2 mins and it still times out. The region, table and key are OK as far as we saw by adding logs on index.js. In terms of permissions, the role of the lambda (LambdaExecRole) allows the actions DeleteItem, DescribeTable, GetItem, ListTables,PutItem, Query, Scan and UpdateItem on * resources. There is no error of any kind in cloudWatch but the time out itself.
Doing the get-item from the command line on the same table with the same key returns the expected config.
Any suggestions are most appreciated

**Comment by IanMeyers** [comment]
Because this is a timeout rather than an exception, this suggests that your lambda function is unable to route to DynamoDB that resides on a public IP address. There's a guide in the documentation about VPC setup, but in short the Lambda function needs to attached ENI's in a private Subnet which then route via a NAT or Internet Gateway to get to DynamoDB. Alternatively you can use a DynamoDB Private Endpoint in VPC. Happy to review the VPC layout if that helps, but it's almost certainly routing related.

**Comment by landoooo** [comment]
You are right. The lambda couldnt reach dynamoDB beacuse of some misconfiguration on a DNS. Thanks to your comments our infra team manage to fix the routing. Thanks Ian!
