### ISSUE TITLE
The connection to Redshift will fail if the password contains special character

### ISSUE THREAD

**Issue by canyousayyes** [awslabs/aws-lambda-redshift-loader#21]
Hello,

I just noticed that the loader is updated to version 2.0 and it is using another DB client.
I tried to use the loader in my lambda function, but resulting in an error message when connecting to Redshift:
`Error: getaddrinfo ENOTFOUND`

Upon some inspection, I found the reason is that my DB password contains some special characters.
And I found that if I encode them properly, I can connect to Redshift without error.

e.g.

`postgres://hello:#123@abc.redshift.amazonaws.com:5439/db` will fail, while
`postgres://hello:%23123@abc.redshift.amazonaws.com:5439/db` will succeed.

Perhaps a `encodeURIComponent` will solve the problem?

Thanks,
Gene Ng

**Comment by IanMeyers** [comment]
Thanks for reporting this Gene. Just to confirm the issue so that I fix the right thing, can you confirm that if you url encode the password, and then encrypt it via the setup.js script, you are able to sign in, but if you do not url encode it prior to encrypting and putting into the confirmation you cannot connect?

Ian

**Comment by IanMeyers** [comment]
Fixed in dist 2.0.1
