### ISSUE TITLE
The loader did not response to the put events in sub-directories

### ISSUE THREAD

**Issue by canyousayyes** [awslabs/aws-lambda-redshift-loader#5]
Hello, I am using this loader since the version 1.1.

The workflow is fine, except that if I upload the file in the sub-directories of the watched bucket, the file is not loaded to Redshift, and the log will say `unable to load configuration for [path]`

e.g.
I set the value of "Enter the S3 Bucket & Prefix to watch for files" to be `mybucket/metric`
When I upload a file exactly to `mybucket/metric`, it will be loaded to Redshift, which is nice.
But when I upload a file to `mubucket/metric/2015/03`, the lambda won't do anything.

How can I setup the configuration so that lambda will also response to sub-directory upload? Thank you.

**Comment by IanMeyers** [comment]
Hello,

Thanks for the question, and glad to hear the tool is working for you. If you want to implement the pattern that you've described, then create the configuration with the s3Prefix as 'mybucket/metric'. Then use a filenameFilterRegex (for example) of '2015\/?[\d]+\/?[\d]+\/.*.csv', which would allow you to load all files which are 'CSV', and which appear in s3 prefixes with format 2015/MM/DD and so on.

However, if you needed to have different configurations for subsets of the prefixes, then you'd need to create a separate configuration for each. Because they are stored in Dynamo DB, there's no performance penalty for doing this, but you would probably want to clean them up over time. You could also programmatically roll the 'today' configuration to a 'tomorrow' configuration, so that you only had 2 configurations, etc.

HTH,

Ian

**Comment by canyousayyes** [comment]
Hello Ian,

I have tried your solution, unfortunately it doesn't work.

I guess the reason is that, when a file is uploaded to S3, the directory path is used as a key to search the matching config in dynamoDB, so the directory path must have an exact match with the Lambda configuration. Therefore, a sub-directory path cannot be matched.

The regex filtering is done after the path matching, so it doesn't work either.

Regards,
Gene

**Comment by IanMeyers** [comment]
Yes of course you are right. I will work on a solution to this and update this issue. I see that you are using a prefix format of `mubucket/metric/<YYYY>/<MM>`. Would you be open to using a format such as `mubucket/metric/y=<YYYY>/mm=<MM>`, which would be similar to the way that Hive treats table partitions?

If so I have a solution that I think will work fine.

**Comment by IanMeyers** [comment]
Hello,

I've pushed version 1.1.2 that now supports wildcard paths using a Hive like partitioning structure of <name>=<value>. As suggested in the previous comment, you can now use dynamic paths for your requirement if you prefix the configuration and bucket structure with a name for each of the dynamic portions.

Do let us know how you get on.

Thx,

Ian
