### ISSUE TITLE
S3 Secret Key

### ISSUE THREAD

**Issue by isac** [awslabs/aws-lambda-redshift-loader#55]
More of a question than an issue.
I wonder why there's a need to specify an access/secret key for Redshift to access S3?
Shouldn't the lambda function be able to receive AWSCredentials from the role it's running on and from those credentials get an accesskey, secretkey and any token needed?

Example below on how I've done it successfully with a Lambda in Java.

``` Java
StringBuilder copy = new StringBuilder();
AWSCredentials creds = credentialsProvider.getCredentials();
copy.append("COPY " + table + " ("+columns+") ");
copy.append("FROM 's3://" + srcBucket + "/" + srcKey + "' ");
copy.append("CREDENTIALS 'aws_access_key_id=" + creds.getAWSAccessKeyId());
copy.append(";aws_secret_access_key=" + creds.getAWSSecretKey());
if(creds instanceof AWSSessionCredentials) {
            copy.append(";token=");
            copy.append(((AWSSessionCredentials) creds).getSessionToken());
}


```

**Comment by IanMeyers** [comment]
Hello,

This was a good idea, so I've added this support in the 2.1.0 version. You can now delete the s3 access key and secret key from the configuration, and the loader will use an STS token from the Lambda execution role. This role must have s3:Get and s3:List in order to work properly. You can of course continue to use a separate set of access and secret keys from that of the Lambda role if you so desire.

Thanks for the suggestion.

Ian
