### ISSUE TITLE
Unable to unlock batches in locked status

### ISSUE THREAD

**Issue by VikeshKara** [awslabs/aws-lambda-redshift-loader#57]
Hi,
I'm currently ending up with batches being in locked state and the loader trying to write to them resulting in error. I tried to unlock them but ending up with the following message:

"Batch <batchid> is not currently allocated as the open batch for Load Configuration on <s3Prefix> Use reprocessBatch.js to rerun the load of this Batch."

So, when running the batch with reprocessBatch.js, the files are processed, what happens with the old batch file, cause to my understanding its still there with the locked state, and the loader is trying to write to it, ending up with follwing message in the logs.

Reload of Configuration Complete after attempting to write to Locked Batch Attempt 1, continuing doing so for 60 secs.

If we run the reprocessBatch.js the files in the "old" locked batch will end up in a new batch with open status? Should we delete the "old" batch which is locked? And how would one do that? Any pointers appreciated.

**Comment by IanMeyers** [comment]
Hello,

Sorry to hear you are having this issue. Can you have a look at the batch ID on the configuration item in DynamoDB, and see what value it has? If it points to a locked batch that you've reprocessed, then unlockBatch.js should definitely fix the issue. If not, then you can just reprocess a failed batch and leave it in error state, as the files that were referenced have been reprocessed into a new batch.

What's perhaps more important is why batches are ending up as locked and never moving to error or complete status. This tends to be because the lambda function timeout is too short, and the module is being terminated while the redshift COPY is still executing. Can you look at increasing your timeout and looking for timeout messages in your CloudWatch Logs?

Thx,

Ian

**Comment by VikeshKara** [comment]
Hi,
I increased the timeout of the lambda and it seems to have done the trick of batches being processed, not ending up in locked status. 

A question though, when i'm ending up with files being written to locked batches, what is the appropriate steps to take?
1. Try to unlock batch, if unlock failed.
2. Reprocess the batch.
3. When the reprocessing of a batch is done, I'm supposed to try unlocking the batch so it can go into it's life-cycle process, and ending up in either error or complete status, if it doesn't I have similar issue to the one solved above?

Thx for the reply!
Br,
Vikesh

**Comment by IanMeyers** [comment]
Glad to hear it. When you have reprocessed a batch, it's files will have be resubmitted to the current batch for the prefix. Nothing needs to be done to the existing batch, but we could change its state to 'reprocessed' if that would help?

**Comment by VikeshKara** [comment]
Hi,
Yes, changing the state to reprocessed would be nice and very helpful.

Br,
Vikesh

**Comment by IanMeyers** [comment]
Done on d09be97a8d20755c385c4e3179cbbff9347a59e5
